sudo: false
language: cpp
compiler: gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

before_install:
  - pip install --user cpp-coveralls

install:
  - make

script:
  - make test
  - make gcov

after_success:
  - coveralls --exclude googletest --exclude ".*_unittest.cc" --gcov-options '\-lp'
  - bash <(curl -s https://codecov.io/bash) -t a25440ca-8d64-49b8-9df3-41bdb3fba44b -X gcov